name: release
on:
  - push
jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npm run build
      - run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/key.json
      - run: npm run deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
        if: github.ref == 'refs/heads/main'
